### ISSUE TITLE
Cannot destroy blocks on Headless Server due to non-fatal NPE

### ISSUE THREAD

**Issue by jdrueckert** [Terasology/Minimap#34]
### What you were trying to do

Destroy a block on a client connected to a headless server hosting a world with `Minimap` enabled (e.g. Metal Renegades).

### What actually happened

The block was not destroyed.
The headless server logs showed an NPE but the server didn't crash.

### Log Details

```
12:06:57.169 [main] ERROR o.t.e.network.internal.NetClient - Error processing event
java.lang.NullPointerException: null
        at org.terasology.logic.players.DefaultMinimapSystem.onDestroyBlock(DefaultMinimapSystem.java:119)
        at org.terasology.logic.players.DefaultMinimapSystemMethodAccess.invoke(Unknown Source)
        at org.terasology.engine.entitySystem.event.internal.EventSystemImpl$ByteCodeEventHandlerInfo.invoke(EventSystemImpl.java:379)
        at org.terasology.engine.entitySystem.event.internal.EventSystemImpl.sendStandardEvent(EventSystemImpl.java:244)
        at org.terasology.engine.entitySystem.event.internal.EventSystemImpl.send(EventSystemImpl.java:235)
        [...]
        at org.terasology.engine.entitySystem.entity.internal.BaseEntityRef.send(BaseEntityRef.java:190)
        at org.terasology.engine.logic.health.EntityDestructionAuthoritySystem.onDestroy(EntityDestructionAuthoritySystem.java:24)
        at org.terasology.engine.logic.health.EntityDestructionAuthoritySystemMethodAccess.invoke(Unknown Source)
        at org.terasology.engine.entitySystem.event.internal.EventSystemImpl$ByteCodeEventHandlerInfo.invoke(EventSystemImpl.java:379)
        at org.terasology.engine.entitySystem.event.internal.EventSystemImpl.sendStandardEvent(EventSystemImpl.java:244)
        at org.terasology.engine.entitySystem.event.internal.EventSystemImpl.send(EventSystemImpl.java:235)
        [...]
        at org.terasology.engine.entitySystem.entity.internal.BaseEntityRef.send(BaseEntityRef.java:190)
        at org.terasology.module.health.systems.DamageAuthoritySystem.doDamage(DamageAuthoritySystem.java:103)
```

### Additional Info

The current assumption is that this is due to the fact that the headless server does not have a `NuiManager` and thus, no HUD elements.
Accordingly, the attempt to access `updateLocation` on an instance of `MinimapHUDElement` will result in a null pointer exception.

One possible approach to fix this is to make `DefaultMinimapSystem` a client-only system such that it will not be present on the headless server in the first place as the headless server in comparison to a headed server does not have a client attached to it.

**Comment by jdrueckert** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Release v5.2.0](https://trello.com/c/iI2iaodH/181-release-v520)
